name: 提出建议
description: 分享你的看法
title: "[建议]: "
labels: ["优化改进(opt & imp)"]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢你能够向我们提出你的看法!

        请填写以下内容,详细描述你对当前版本库已有内容的看法.提供更多信息可以帮助我们更好地理解和评估你的看法.

  - type: input
    id: suggestion-title
    attributes:
      label: 标题
      description: 用一句话简要概述你的看法
    validations:
      required: true

  - type: textarea
    id: suggestion-details
    attributes:
      label: 详情
      description: |
        请详细说明你的看法:
        - 你认为某个具体的功能怎么样?
        - 我们在哪个地方做的好,在哪个地方做的不好?
        - 你认为我们要怎么样才能做得更好?
    validations:
      required: true

  - type: input
    id: suggestion-benefit
    attributes:
      label: 效益
      description: 你认为我们在做到了你的建议后能获得什么效益?
    validations:
      required: true

  - type: checkboxes
    id: additional-info
    attributes:
      label: 请确认以下内容
      options:
        - label: 我确认这个建议是真实有效的且可以实施的.
          required: true
        - label: 我已经查看了现有的 [Issue Tracker](https://github.com/Spectrollay/minecraft_repository/issues) 并确认提交的建议没有重复.
          required: true

  - type: input
    id: name
    attributes:
      label: 你的名称
      description: (可选)用于可能的贡献展示
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: 联系邮箱
      description: (可选)用于可能的贡献展示
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 感谢你的建议!我们将在在后续开发中评估你的建议.
